services:
  system-api:
    image: thalissoncastrog/system-api-dotnet:1.0.1
    env_file:
      - ./src/SystemAPI/.env
    ports:
      - "8080:8080"
    depends_on: ["sqlserver"]
    networks:
      app-network:

  sqlserver:
    image: thalissoncastrog/sqlserver:1.0.1
    ports:
      - "1434:1433"
    hostname: sqlserver
    container_name: sqlserver
    networks:
      app-network:
        aliases:
          - "sqlserver"

networks:
  app-network:
    driver: bridge
